channels:
  - conda-forge
dependencies:
  # dependencies
  - qpot
  - gmattensor
  - xtensor

  # optional dependencies
  - xsimd

  # build tools
  - cmake
  - setuptools_scm

  # Python API
  - python
  - pyxtensor

  # to run tests
  - catch2
  - goosefem
  - numpy
  - h5py
